"""Orchestrator architecture primitives for ECOS."""

from ecos.orchestrator.engine import Orchestrator
from ecos.orchestrator.exceptions import (
    ApprovalMissingError,
    AuthorizationExpiredError,
    CycleDetectedError,
    DuplicateExecutorError,
    EngineNotRegisteredError,
    ExecutorIncompatibleError,
    GovernanceMissingError,
    IncompatibleApprovalError,
    IncompatiblePlanError,
    IncompatibleSessionError,
    InvalidConditionError,
    InvalidDependencyError,
    InvalidResultError,
    InvalidRetryError,
    InvalidTimeoutError,
    OperatorNotAllowedError,
    PipelineInconsistentError,
    RequiredOutputMissingError,
    RequiredStageFailedError,
)
from ecos.orchestrator.executor import EngineExecutor
from ecos.orchestrator.models import (
    ApprovalState,
    ApprovalStatus,
    EngineExecution,
    EngineInvocationContext,
    EngineStageResult,
    ExecutionEvent,
    ExecutionMode,
    ExecutionPlan,
    ExecutionResult,
    ExecutionState,
    ExecutionStatus,
    ExecutionStep,
    FailureClassification,
    FailureReport,
    GovernanceState,
    OrchestrationConfig,
    OrchestrationInput,
    OrchestrationMode,
    OrchestrationResult,
    PipelineExecutionStatus,
    ResumableOrchestrationState,
    StageExecutionStatus,
    TimelineEntry,
)
from ecos.orchestrator.provider import OrchestratorProvider
from ecos.orchestrator.service import OrchestratorService

__all__ = [
    "ApprovalMissingError",
    "ApprovalState",
    "ApprovalStatus",
    "AuthorizationExpiredError",
    "CycleDetectedError",
    "DuplicateExecutorError",
    "EngineExecutor",
    "EngineExecution",
    "EngineInvocationContext",
    "EngineNotRegisteredError",
    "EngineStageResult",
    "ExecutorIncompatibleError",
    "ExecutionEvent",
    "ExecutionMode",
    "ExecutionPlan",
    "ExecutionResult",
    "ExecutionState",
    "ExecutionStatus",
    "ExecutionStep",
    "FailureClassification",
    "FailureReport",
    "GovernanceMissingError",
    "GovernanceState",
    "IncompatibleApprovalError",
    "IncompatiblePlanError",
    "IncompatibleSessionError",
    "InvalidConditionError",
    "InvalidDependencyError",
    "InvalidResultError",
    "InvalidRetryError",
    "InvalidTimeoutError",
    "OperatorNotAllowedError",
    "OrchestrationConfig",
    "OrchestrationInput",
    "OrchestrationMode",
    "OrchestrationResult",
    "Orchestrator",
    "OrchestratorProvider",
    "OrchestratorService",
    "PipelineExecutionStatus",
    "PipelineInconsistentError",
    "RequiredOutputMissingError",
    "RequiredStageFailedError",
    "ResumableOrchestrationState",
    "StageExecutionStatus",
    "TimelineEntry",
]
