import { Mic, MicOff, Minimize2, Send, Volume2, VolumeX, X } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { ApiError } from "../api";
import { useAuth } from "../auth";
import { isSaraAction, runSaraAction } from "./saraActions";
import { getSaraSessionState, parseRetryAfter, sendSaraInteraction } from "./saraApi";
import { SaraHologram } from "./SaraHologram";
import { loadSaraPreferences, saveSaraPreferences } from "./saraStorage";
import type { SaraHistoryItem, SaraMode, SaraPoint, SaraResponse, SaraRuntime, SaraRuntimeState, SaraState } from "./saraTypes";
import "./sara-live.css";

const greeting = "Sou a SARA, uma interface cognitiva do E.C.O.S. Posso registrar objetivos e abrir áreas permitidas; decisões, aprovações e execuções permanecem sob governança humana.";
const ttsUrl = import.meta.env.VITE_SARA_TTS_URL as string | undefined;
const labels: Record<SaraState, string> = { idle: "DISPONÍVEL", listening: "ESCUTANDO", thinking: "PROCESSANDO", speaking: "TRANSMITINDO", offline: "INDISPONÍVEL", error: "ERRO", waiting_approval: "AGUARDANDO APROVAÇÃO", executing: "ACOMPANHANDO EXECUÇÃO" };
const terminalRuntimeStates = new Set<SaraRuntimeState>(["completed", "error"]);
const runtimePresenceState = (runtimeState: SaraRuntimeState): SaraState => runtimeState === "completed" ? "idle" : runtimeState;

export function SaraPresenceLayer() {
  const { auth } = useAuth(); const navigate = useNavigate(); const location = useLocation();
  const org = auth!.organization.organization_id, user = auth!.principal.user_id;
  const initial = useMemo(() => loadSaraPreferences(org, user), [org, user]);
  const [mode, setMode] = useState<SaraMode>(initial.mode); const [position, setPosition] = useState(initial.position);
  const [voice, setVoice] = useState(initial.voice); const [state, setState] = useState<SaraState>("idle");
  const [caption, setCaption] = useState(greeting); const [input, setInput] = useState(""); const [sessionId, setSessionId] = useState<string | null>(null); const [interaction, setInteraction] = useState<SaraResponse | null>(null);
  const [speakPulse, setSpeakPulse] = useState(0); const audio = useRef<HTMLAudioElement | null>(null); const audioUrl = useRef<string | null>(null);
  const speechTimer = useRef<number | null>(null); const amplitudeRaf = useRef<number | null>(null); const audioContext = useRef<AudioContext | null>(null);
  const history = useRef<SaraHistoryItem[]>([]); const inputRef = useRef<HTMLInputElement>(null); const previousFocus = useRef<HTMLElement | null>(null);
  const drag = useRef({ active: false, moved: false, x: 0, y: 0, origin: initial.position });
  const recognition = useRef<SpeechRecognitionLike | null>(null);
  const confirmedPresenceState = useRef<SaraState>("idle"); const runtimeRef = useRef<SaraRuntime | null>(null); const interactionAbort = useRef<AbortController | null>(null); const interactionSequence = useRef(0); const interactionPending = useRef(false);
  const reducedMotion = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
  const persist = useCallback((nextMode = mode, nextPosition = position, nextVoice = voice) => saveSaraPreferences(org, user, { mode: nextMode, position: nextPosition, voice: nextVoice, expansionAllowed: initial.expansionAllowed }), [initial.expansionAllowed, mode, org, position, user, voice]);
  const changeMode = useCallback((next: SaraMode) => { setMode(next); persist(next); }, [persist]);
  const clamp = useCallback((point: SaraPoint): SaraPoint => ({ x: Math.max(8, Math.min(point.x, window.innerWidth - 128)), y: Math.max(8, Math.min(point.y, window.innerHeight - 128)) }), []);
  useEffect(() => { if (mode === "full") { previousFocus.current = document.activeElement as HTMLElement; window.setTimeout(() => inputRef.current?.focus(), 0); } else previousFocus.current?.focus?.(); }, [mode]);
  useEffect(() => { const resize = () => setPosition((old) => { const next = clamp(old); persist(mode, next); return next; }); window.addEventListener("resize", resize); return () => window.removeEventListener("resize", resize); }, [clamp, mode, persist]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { const target = event.target; const typing = target instanceof Element && target.matches("input,textarea,[contenteditable=true]"); if (!typing && event.altKey && event.key.toLowerCase() === "s") { event.preventDefault(); changeMode(mode === "closed" ? "full" : "closed"); } if (event.key === "Escape" && mode === "full") changeMode("mini"); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [changeMode, mode]);
  const pulseSpeech = useCallback((intensity = 1) => setSpeakPulse((old) => old + Math.max(.05, Math.min(1.3, intensity))), []);
  const stopSpeechEffects = useCallback(() => { if (speechTimer.current !== null) window.clearInterval(speechTimer.current); speechTimer.current = null; if (amplitudeRaf.current !== null) cancelAnimationFrame(amplitudeRaf.current); amplitudeRaf.current = null; }, []);
  const startTimedPulses = useCallback((text: string, durationMs?: number) => { stopSpeechEffects(); const words = Math.max(1, text.trim().split(/\s+/).length); const interval = Math.max(70, Math.min(360, (durationMs ?? words * 190) / words)); speechTimer.current = window.setInterval(() => pulseSpeech(.72), interval); }, [pulseSpeech, stopSpeechEffects]);
  const stopAudio = useCallback(() => { stopSpeechEffects(); audio.current?.pause(); audio.current = null; if (audioUrl.current) URL.revokeObjectURL(audioUrl.current); audioUrl.current = null; }, [stopSpeechEffects]);
  useEffect(() => () => { interactionSequence.current++; interactionAbort.current?.abort(); recognition.current?.abort?.(); window.speechSynthesis?.cancel(); stopAudio(); void audioContext.current?.close(); audioContext.current = null; }, [stopAudio]);
  const applyConfirmedRuntime = useCallback((runtime: SaraRuntime) => { runtimeRef.current = runtime; const confirmed = runtimePresenceState(runtime.state); confirmedPresenceState.current = confirmed; setState((current) => current === "speaking" || current === "listening" ? current : confirmed); }, []);
  const speakBrowser = useCallback((text: string) => { if (!window.speechSynthesis) return setState(confirmedPresenceState.current); window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = "pt-BR"; let boundaries = 0; utterance.onstart = () => { setState("speaking"); startTimedPulses(text); }; utterance.onboundary = () => { boundaries++; if (boundaries === 1) stopSpeechEffects(); pulseSpeech(1); }; utterance.onend = () => { stopSpeechEffects(); setState(confirmedPresenceState.current); }; utterance.onerror = () => { stopSpeechEffects(); setState("error"); }; window.speechSynthesis.speak(utterance); }, [pulseSpeech, startTimedPulses, stopSpeechEffects]);
  const speak = useCallback(async (text: string) => { if (!voice) return setState(confirmedPresenceState.current); stopAudio(); if (!ttsUrl) return speakBrowser(text); try { const response = await fetch(ttsUrl, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ text }) }); if (!response.ok) throw new Error("TTS unavailable"); const blob = await response.blob(); const url = URL.createObjectURL(blob); const player = new Audio(url); audio.current = player; audioUrl.current = url; player.onloadedmetadata = () => startTimedPulses(text, Number.isFinite(player.duration) ? player.duration * 1000 : undefined); player.onplay = () => { setState("speaking"); try { const Ctx = window.AudioContext; if (!Ctx) return; const context = audioContext.current ?? new Ctx(); audioContext.current = context; const analyser = context.createAnalyser(); analyser.fftSize = 256; const source = context.createMediaElementSource(player); source.connect(analyser); analyser.connect(context.destination); const bytes = new Uint8Array(analyser.frequencyBinCount); const pump = () => { analyser.getByteTimeDomainData(bytes); let sum = 0; for (const byte of bytes) { const value = (byte - 128) / 128; sum += value * value; } pulseSpeech(Math.min(1.3, Math.sqrt(sum / bytes.length) * 4.2)); if (!player.paused && !player.ended) amplitudeRaf.current = requestAnimationFrame(pump); }; amplitudeRaf.current = requestAnimationFrame(pump); } catch { /* timed word pulses remain the safe fallback */ } }; player.onended = () => { stopAudio(); setState(confirmedPresenceState.current); }; player.onerror = () => { stopAudio(); speakBrowser(text); }; await player.play(); } catch { stopAudio(); speakBrowser(text); } }, [pulseSpeech, speakBrowser, startTimedPulses, stopAudio, voice]);
  const send = useCallback(async (forced?: string) => { const message = (forced ?? input).trim().slice(0, 2000); if (!message || interactionPending.current) return; interactionPending.current = true; const sequence = ++interactionSequence.current; interactionAbort.current?.abort(); const controller = new AbortController(); interactionAbort.current = controller; setInput(""); try { const result = await sendSaraInteraction(message, history.current, sessionId, location.pathname, controller.signal); if (controller.signal.aborted || sequence !== interactionSequence.current) return; const additions: SaraHistoryItem[] = [{ role: "user", content: message }, { role: "assistant", content: result.response }]; history.current = [...history.current, ...additions].slice(-12); setInteraction(result); setSessionId(result.session_id); setCaption(result.response); applyConfirmedRuntime(result.runtime); result.ui_actions.filter(isSaraAction).forEach((action) => runSaraAction(action, navigate, () => changeMode("mini"))); if (result.unavailable) setState("offline"); else if (voice) void speak(result.response); } catch (error) { if (controller.signal.aborted || sequence !== interactionSequence.current) return; setState((error instanceof ApiError && error.status === 0) || error instanceof TypeError ? "offline" : "error"); setCaption(error instanceof Error ? error.message : "SARA indisponível no momento."); } finally { if (interactionAbort.current === controller) interactionAbort.current = null; if (sequence === interactionSequence.current) interactionPending.current = false; } }, [applyConfirmedRuntime, changeMode, input, location.pathname, navigate, sessionId, speak, voice]);
  useEffect(() => { let active = true; let timer: number | null = null; let request: AbortController | null = null; let etag: string | null = null; const selectedSession = sessionId; if (!selectedSession || runtimeRef.current && terminalRuntimeStates.has(runtimeRef.current.state)) return; const schedule = (delay: number | null) => { if (!active || delay === null) return; timer = window.setTimeout(() => { void poll(); }, delay); }; const poll = async () => { if (!active) return; request = new AbortController(); try { const result = await getSaraSessionState(selectedSession, etag, request.signal); if (!active || selectedSession !== sessionId) return; etag = result.etag; if (result.notModified) { schedule(result.retryAfterMs); return; } if (!result.state) return; const runtime = result.state.runtime; setInteraction((current) => current?.session_id === selectedSession ? { ...current, runtime } : current); applyConfirmedRuntime(runtime); if (!terminalRuntimeStates.has(runtime.state)) schedule(result.retryAfterMs); } catch (error) { if (!active || request.signal.aborted) return; setState("offline"); const retry = error instanceof ApiError ? parseRetryAfter(error.retryAfter) : null; schedule(retry ?? 5000); } }; schedule(0); return () => { active = false; if (timer !== null) window.clearTimeout(timer); request?.abort(); }; }, [applyConfirmedRuntime, sessionId]);
  const toggleMic = () => { if (state === "listening") return recognition.current?.stop(); const Constructor = (window as SpeechWindow).SpeechRecognition ?? (window as SpeechWindow).webkitSpeechRecognition; if (!Constructor) { setState("error"); setCaption("O reconhecimento de voz não está disponível neste navegador. Use o campo de texto."); return; } const rec = new Constructor(); rec.lang = "pt-BR"; rec.interimResults = true; rec.onresult = (event) => { const value = Array.from(event.results).map((item) => item[0].transcript).join(" "); setInput(value); if (event.results[event.results.length - 1]?.isFinal) void send(value); }; rec.onend = () => setState((old) => old === "listening" ? "idle" : old); rec.onerror = () => setState("error"); recognition.current = rec; setState("listening"); rec.start(); };
  const pointerDown = (event: React.PointerEvent) => { if (mode !== "mini") return; drag.current = { active: true, moved: false, x: event.clientX, y: event.clientY, origin: position }; event.currentTarget.setPointerCapture?.(event.pointerId); };
  const pointerMove = (event: React.PointerEvent) => { if (!drag.current.active || mode !== "mini") return; const dx = event.clientX - drag.current.x, dy = event.clientY - drag.current.y; if (Math.abs(dx) + Math.abs(dy) > 5) drag.current.moved = true; setPosition(clamp({ x: drag.current.origin.x + dx, y: drag.current.origin.y + dy })); };
  const pointerUp = () => { if (!drag.current.active) return; drag.current.active = false; if (mode === "mini" && !drag.current.moved) changeMode("full"); else persist(mode, position); };
  const statusLabel = interaction?.runtime.state === "completed" && state === "idle" ? "CONCLUÍDO" : labels[state];
  return <div className={`sh-root sh-${mode}`} data-session-id={interaction?.session_id} data-interaction-id={interaction?.interaction_id} data-runtime-state={interaction?.runtime.state} data-unavailable={interaction?.unavailable} data-incomplete-context={interaction?.incomplete_context}>
    {mode === "closed" ? <button className="sh-summon" aria-label="Invocar SARA" onClick={() => changeMode("full")}><span className="sh-halo" /><span className="sh-spark" /><span className="sh-label">SARA</span></button> : null}
    {mode !== "closed" ? <div className="sh-holo" role={mode === "full" ? "dialog" : undefined} aria-modal={mode === "full" ? "true" : undefined} aria-label="Presença SARA">
      {mode === "full" ? <div className="sh-dim" /> : null}
      <div className="sh-stage" style={mode === "mini" ? { left: position.x, top: position.y } : undefined} onPointerDown={pointerDown} onPointerMove={pointerMove} onPointerUp={pointerUp} onPointerCancel={pointerUp}>
        <div className="sh-orbit"><SaraHologram mode={mode} state={state} reducedMotion={reducedMotion} speakPulse={speakPulse} /></div><div className="sh-name"><strong>S A R A</strong><span>INTERFACE COGNITIVA</span></div>
      </div>
      {mode === "full" ? <div className="sh-tools"><button aria-label="Minimizar SARA" onClick={() => changeMode("mini")}><Minimize2 /></button><button aria-label="Fechar SARA" onClick={() => { stopAudio(); window.speechSynthesis?.cancel(); changeMode("closed"); }}><X /></button></div> : null}
      {mode === "full" ? <><div className="sh-status" aria-live="polite"><i />{statusLabel}</div><div className="sh-caption"><span>S A R A</span><p>{caption}</p></div><form className="sh-console" onSubmit={(event) => { event.preventDefault(); void send(); }}><button type="button" aria-label={state === "listening" ? "Parar microfone" : "Usar microfone"} onClick={toggleMic}>{state === "listening" ? <MicOff /> : <Mic />}</button><label><span className="sr-only">Objetivo ou interação cognitiva</span><input ref={inputRef} maxLength={2000} value={input} onChange={(event) => setInput(event.target.value)} placeholder="Digite um objetivo ou interação..." /></label><button type="submit" aria-label="Enviar interação" disabled={!input.trim() || state === "thinking"}><Send /></button><button type="button" aria-label={voice ? "Desativar voz" : "Ativar voz"} onClick={() => { setVoice(!voice); persist(mode, position, !voice); window.speechSynthesis?.cancel(); }}>{voice ? <Volume2 /> : <VolumeX />}</button></form></> : null}
    </div> : null}
  </div>;
}

type SpeechRecognitionEventLike = { results: ArrayLike<{ 0: { transcript: string }; isFinal: boolean }> };
type SpeechRecognitionLike = { start(): void; stop(): void; abort?(): void; onresult: ((event: SpeechRecognitionEventLike) => void) | null; onend: (() => void) | null; onerror: (() => void) | null; lang: string; interimResults: boolean };
type SpeechWindow = Window & { SpeechRecognition?: new () => SpeechRecognitionLike; webkitSpeechRecognition?: new () => SpeechRecognitionLike };
