import { fireEvent, render } from "@testing-library/react";
import { createElement } from "react";
import { afterEach, describe, expect, it, vi } from "vitest";
import { SaraHologram } from "./SaraHologram";
import { EFFECT_LIMITS, FULL_PARTICLE_COUNT, MINI_PARTICLE_COUNT, NEURAL_NODE_COUNT, ORBITAL_ARC_COUNT, REDUCED_PARTICLE_COUNT, createSaraHologramEngine, makeParticleSystem, mapVisualState, planeBasis } from "./saraHologramEngine";

afterEach(()=>vi.restoreAllMocks());
describe("SARA volumetric hologram engine",()=>{
  it("creates the complete official system once with golden-angle bands",()=>{const random=vi.fn(()=>.5),system=makeParticleSystem(random);expect(system.particles).toHaveLength(FULL_PARTICLE_COUNT);expect(system.arcs).toHaveLength(ORBITAL_ARC_COUNT);expect(system.tickRings).toHaveLength(3);expect(system.nodes).toHaveLength(NEURAL_NODE_COUNT);expect(planeBasis(0,0,1)).toHaveLength(6);});
  it("maps ECOS states onto the same visual engine",()=>{expect(mapVisualState("waiting_approval")).toBe("thinking");expect(mapVisualState("executing")).toBe("speaking");expect(mapVisualState("offline")).toBe("idle");expect(mapVisualState("error")).toBe("idle");});
  it("reports full, mini and reduced processing budgets",()=>{const view=render(createElement(SaraHologram,{mode:"full",state:"idle",reducedMotion:false,speakPulse:0}));expect(view.container.querySelector("canvas")).toHaveAttribute("data-particles",String(FULL_PARTICLE_COUNT));view.rerender(createElement(SaraHologram,{mode:"mini",state:"idle",reducedMotion:false,speakPulse:0}));expect(view.container.querySelector("canvas")).toHaveAttribute("data-particles",String(MINI_PARTICLE_COUNT));view.rerender(createElement(SaraHologram,{mode:"full",state:"idle",reducedMotion:true,speakPulse:0}));expect(view.container.querySelector("canvas")).toHaveAttribute("data-particles",String(REDUCED_PARTICLE_COUNT));});
  it("rotates from pointer input only in full mode",()=>{const view=render(createElement(SaraHologram,{mode:"full",state:"idle",reducedMotion:false,speakPulse:0})),canvas=view.container.querySelector("canvas")!;fireEvent.pointerDown(canvas,{pointerId:1,clientX:20,clientY:20});fireEvent.pointerMove(canvas,{pointerId:1,clientX:60,clientY:40});fireEvent.pointerUp(canvas,{pointerId:1});view.rerender(createElement(SaraHologram,{mode:"mini",state:"idle",reducedMotion:false,speakPulse:0}));fireEvent.pointerDown(canvas,{pointerId:2,clientX:20,clientY:20});fireEvent.pointerMove(canvas,{pointerId:2,clientX:80,clientY:80});expect(canvas).toBeInTheDocument();});
  it("pauses while hidden, resizes, and cleans RAF and visibility listeners",()=>{const canvas=document.createElement("canvas"),cancel=vi.spyOn(window,"cancelAnimationFrame"),remove=vi.spyOn(document,"removeEventListener"),engine=createSaraHologramEngine(canvas,{mode:"full",state:"speaking",reducedMotion:false,speakPulse:1});engine.resize();engine.start();Object.defineProperty(document,"hidden",{configurable:true,value:true});fireEvent(document,new Event("visibilitychange"));engine.destroy();expect(cancel).toHaveBeenCalled();expect(remove).toHaveBeenCalledWith("visibilitychange",expect.any(Function));});
  it("declares bounded transient effect arrays",()=>{expect(EFFECT_LIMITS).toEqual({flares:24,waves:12,sparks:96,comets:40,rings:8,bolts:16});});
});
